In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
data = pd.read_csv("play_tennis.csv")
data.drop(columns ="day", inplace = True)
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

Problem 1:
Outlook = Sunny , Temp = Hot , Humidity = High , Wind = Weak

Play yes or no??

P(Yes /Sunny,Hot, HIgh, Weak) = P(sunny/Yes) * P(hot/yes) * P(high/yes) *P(Weak/yes) * p(yes  )

In [11]:
py = 9/14
pn = 5/14

In [12]:
pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [13]:
pon = 0
prn = 2/5
psn = 3/5
psy = 2/5
poy = 4/9
pry = 2/9

In [14]:
pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [15]:
pCoolNo = 1/5
pCoolYes = 3/9
pHotYes = 2/9
pHotNo = 2/5
pMildYes= 4/9
pMildNo = 2/5

In [16]:
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [17]:
phighno = 4/5
pnormalno = 1/5
phighyes = 3/9
pnormalyes= 6/9

In [18]:
pstrongno = 3/5
pweakno = 2/5
pstrongyes = 3/9
pweakyes = 6/9

In [19]:
# Problem 1:
# Outlook = Sunny , Temp = Hot , Humidity = High , Wind = Weak

In [21]:
playyes = py * phighyes * pHotYes * psy *pweakyes
playyes

0.012698412698412698