In [22]:

from sklearn.datasets import fetch_california_housing
import numpy as np
import pandas as pd

In [23]:
X,y = fetch_california_housing(return_X_y=True)

In [24]:
housing = fetch_california_housing()

In [25]:
df = pd.DataFrame(X,y)
df

            0     1         2         3       4         5      6       7
4.526  8.3252  41.0  6.984127  1.023810   322.0  2.555556  37.88 -122.23
3.585  8.3014  21.0  6.238137  0.971880  2401.0  2.109842  37.86 -122.22
3.521  7.2574  52.0  8.288136  1.073446   496.0  2.802260  37.85 -122.24
3.413  5.6431  52.0  5.817352  1.073059   558.0  2.547945  37.85 -122.25
3.422  3.8462  52.0  6.281853  1.081081   565.0  2.181467  37.85 -122.25
...       ...   ...       ...       ...     ...       ...    ...     ...
0.781  1.5603  25.0  5.045455  1.133333   845.0  2.560606  39.48 -121.09
0.771  2.5568  18.0  6.114035  1.315789   356.0  3.122807  39.49 -121.21
0.923  1.7000  17.0  5.205543  1.120092  1007.0  2.325635  39.43 -121.22
0.847  1.8672  18.0  5.329513  1.171920   741.0  2.123209  39.43 -121.32
0.894  2.3886  16.0  5.254717  1.162264  1387.0  2.616981  39.37 -121.24

[20640 rows x 8 columns]

In [26]:
df = pd.DataFrame(
    housing.data,
    columns=housing.feature_names
)

In [27]:
df["price"] = housing.target
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score

In [29]:
lr = LinearRegression()
dt = DecisionTreeRegressor()
svr = SVR()

In [30]:
estimators = [("lr", lr),("dt",dt),("svr", svr)]

In [31]:
for estimator in estimators:
    scores = cross_val_score(estimator[1], X,y,cv = 5, scoring = "r2")
    print(estimator[0],np.mean(scores))

lr 0.5530311140279226
dt 0.3535041933900933
svr -0.11011882232910457

In [32]:
from sklearn.ensemble import VotingRegressor

In [34]:
vr = VotingRegressor(estimators = estimators)
scores = cross_val_score(estimator[1], X,y,cv = 10, scoring = "r2")
print("Voting Regressor",np.mean(scores))

Voting Regressor -0.24618669909509655

In [39]:

vr = VotingRegressor(estimators,weights=[0.7,0.3,0.0])
scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
print(np.round(np.mean(scores),2))

0.56